import fs from "node:fs/promises";
import path from "node:path";
import { Presentation, PresentationFile } from "@oai/artifact-tool";
const ROOT="/Users/carlosm.kampff/Desktop/dev/sbcc-ev-charging-stations", OUT=path.join(ROOT,".video_build/slides");
const C={ink:"#0B0D10",muted:"#5E6673",panel:"#EDEDED",rule:"#B8BCC4",blue:"#3D8DFF",green:"#2E9D64",orange:"#E88935",purple:"#7A4CC2",red:"#D94C4C",white:"#FFFFFF"};
const p=Presentation.create({slideSize:{width:1280,height:720}});
async function img(rel){const b=await fs.readFile(path.join(ROOT,rel));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}
async function wb(dest,b){await fs.writeFile(dest,new Uint8Array(await b.arrayBuffer()))}
function box(s,x,y,w,h,fill=C.panel,line=C.rule,r=0){return s.shapes.add({geometry:r?"roundRect":"rect",position:{left:x,top:y,width:w,height:h},fill,line:{style:"solid",fill:line,width:1},...(r?{borderRadius:r}:{})})}
function tx(s,t,x,y,w,h,size=26,bold=false,color=C.ink,align="left"){const z=s.shapes.add({geometry:"textbox",position:{left:x,top:y,width:w,height:h},fill:"none",line:{style:"solid",fill:"none",width:0}});z.text=t;z.text.style={fontSize:size,typeface:"Helvetica Neue",color,bold,alignment:align,verticalAlignment:"top",autoFit:"shrinkText",insets:{top:0,right:0,bottom:0,left:0}};return z}
function head(s,t,k,n){tx(s,k.toUpperCase(),48,30,520,26,17,true,C.blue);tx(s,t,48,69,1180,70,48,true);tx(s,String(n).padStart(2,"0"),1188,672,44,24,15,false,C.muted,"right")}
function notes(s,n,src=[]){s.speakerNotes.textFrame.setText(`${n}\n\n[Sources]\n${src.map(x=>`- ${x}`).join("\n")}`);s.speakerNotes.setVisible(true)}
const nb=path.join(ROOT,"data_analysis_days_colab.ipynb");

{const s=p.slides.add();s.background.fill=C.white;tx(s,"NOTEBOOK MODEL COMPARISON",48,44,520,28,18,true,C.blue);tx(s,"Forecasting EV charging demand",48,128,540,180,64,true);tx(s,"STL‑ARIMA vs RNN vs Temporal Fusion Transformer",48,340,520,112,30,false,C.muted);tx(s,"Santa Barbara County · daily energy delivered",48,572,500,36,20,false,C.muted);box(s,628,42,604,588,"#F4F7FA",C.rule,14);s.images.add({blob:await img("images/days/tft_forecast.jpg"),contentType:"image/jpeg",alt:"Forecast comparison",fit:"contain",position:{left:650,top:88,width:560,height:470}});tx(s,"TFT wins on RMSE — with important caveats",666,552,526,44,24,true,C.purple);notes(s,"This notebook asks which model best forecasts daily energy delivered by Santa Barbara County's EV charging network?",[nb,path.join(ROOT,"images/days/tft_forecast.jpg")])}

{const s=p.slides.add();s.background.fill=C.white;head(s,"One fair test across all three models","Evaluation design",2);s.images.add({blob:await img("images/days/scope_harmonisation.jpg"),contentType:"image/jpeg",alt:"Reporting scope plot",fit:"contain",position:{left:48,top:170,width:720,height:420}});box(s,812,180,380,126,"#F3F7FD",C.blue,10);tx(s,"1,170 days",840,205,320,46,38,true,C.blue);tx(s,"training · 2022-01-01 to 2025-03-15",840,260,320,28,19,false,C.muted);box(s,812,326,380,126,"#F8F4FC","#CDB8E8",10);tx(s,"502 days",840,351,320,46,38,true,C.purple);tx(s,"held out · no test observations",840,406,320,28,19,false,C.muted);tx(s,"Same origin. Same horizon. Same target.",812,500,380,82,29,true);notes(s,"All three models train on eleven hundred seventy days, then forecast the next five hundred two without seeing any test observation. That long horizon is deliberately difficult.",[nb,path.join(ROOT,"images/days/scope_harmonisation.jpg")])}

{const s=p.slides.add();s.background.fill=C.white;head(s,"Three architectures, three failure modes","How they forecast",3);const xs=[48,456,864],d=[["STL‑ARIMA",C.green,"Decompose seasonality + trend, then model residuals","Transparent and fast\nRisk: trend extrapolation"],["RNN · LSTM",C.orange,"30-day look-back; predict one day and feed it back","Nonlinear memory\nRisk: recursive drift"],["TFT",C.purple,"90-day encoder + calendar; output 502 days directly","Multi-horizon + interpretable\nRisk: calibration"]];for(let i=0;i<3;i++){box(s,xs[i],175,360,432,"#F6F6F6",C.rule,10);box(s,xs[i],175,360,12,d[i][1],d[i][1]);tx(s,d[i][0],xs[i]+24,214,312,52,34,true,d[i][1]);tx(s,d[i][2],xs[i]+24,288,312,118,23);tx(s,d[i][3],xs[i]+24,463,312,90,21,false,C.muted)}notes(s,"STL ARIMA separates seasonality and trend. The RNN uses thirty days of energy history and forecasts recursively. TFT uses ninety days of history plus calendar features, and emits the full horizon in one pass.",[nb])}

{const s=p.slides.add();s.background.fill=C.white;head(s,"TFT makes the smallest absolute forecast error","Results",4);s.charts.add("bar",{position:{left:48,top:170,width:700,height:440},categories:["TFT","STL-ARIMA","RNN"],series:[{name:"RMSE",values:[544.33,904.95,983.91],fill:C.blue}],hasLegend:false,dataLabels:{showValue:true,position:"outEnd"},chartFill:C.white,chartLine:{style:"solid",width:0,fill:C.white},plotAreaFill:{type:"none"},plotAreaLine:{style:"solid",width:0,fill:C.white},xAxis:{visible:true,textStyle:{typeface:"Helvetica Neue",fontSize:"18px",color:C.ink}},yAxis:{visible:true,min:0,max:1100,majorUnit:250,majorGridlines:{style:"solid",width:1,fill:C.panel},textStyle:{typeface:"Helvetica Neue",fontSize:"15px",color:C.muted}},barOptions:{direction:"column",grouping:"clustered",gapWidth:65}});box(s,790,172,402,130,"#F8F4FC","#CDB8E8",10);tx(s,"39.8%",820,195,340,52,43,true,C.purple);tx(s,"lower RMSE than STL‑ARIMA",820,254,340,28,21);box(s,790,322,402,130,"#F8F4FC","#CDB8E8",10);tx(s,"44.7%",820,345,340,52,43,true,C.purple);tx(s,"lower RMSE than the RNN",820,404,340,28,21);tx(s,"Also 7.3% better than the random-walk baseline.",790,492,402,82,24,true);notes(s,"STL ARIMA scores RMSE nine hundred four point nine five. The RNN finishes last at nine hundred eighty three point nine one. TFT scores five hundred forty four point three three: thirty nine point eight percent better than STL ARIMA, and forty four point seven percent better than the RNN.",[nb])}

{const s=p.slides.add();s.background.fill=C.white;head(s,"The forecast path explains the ranking","Why TFT won",5);s.images.add({blob:await img("images/days/tft_forecast.jpg"),contentType:"image/jpeg",alt:"Model forecast paths",fit:"contain",position:{left:48,top:156,width:1184,height:420}});tx(s,"STL‑ARIMA overshoots",60,600,340,38,25,true,C.green);tx(s,"RNN compounds error",466,600,340,38,25,true,C.orange);tx(s,"TFT emits one direct path",872,600,340,38,25,true,C.purple);notes(s,"Across five hundred two recursive steps, the RNN's error compounds. STL ARIMA projects a fitted linear trend through a period that rises and then falls. TFT avoids recursive drift and an explicit extrapolated trend.",[nb,path.join(ROOT,"images/days/tft_forecast.jpg")])}

{const s=p.slides.add();s.background.fill=C.white;head(s,"Sensible signal, unreliable uncertainty","Interpretation and caveats",6);s.images.add({blob:await img("images/days/tft_interpretability.jpg"),contentType:"image/jpeg",alt:"TFT variable importance",fit:"contain",position:{left:48,top:156,width:720,height:340}});tx(s,"34.4%",60,516,150,50,40,true,C.purple);tx(s,"weight on recent observed energy",220,522,500,36,22);tx(s,"62.3%",60,580,150,50,40,true,C.purple);tx(s,"weight on annual month seasonality",220,586,500,36,22);box(s,812,175,380,164,"#FEF3F3","#F0B3B3",10);tx(s,"50% coverage",840,204,324,48,36,true,C.red);tx(s,"for a nominal 80% interval",840,264,324,50,21);box(s,812,366,380,164,"#F6F6F6",C.rule,10);tx(s,"One seed · one split",840,397,324,44,31,true);tx(s,"The 7.3% baseline margin is promising, not established.",840,456,324,54,21);notes(s,"TFT anchors the level on recent observed energy, then shapes the future with annual seasonality. But the nominal eighty percent interval covered only fifty percent of actual days, and percentage error remained high on low-demand days.",[nb,path.join(ROOT,"images/days/tft_interpretability.jpg")])}

{const s=p.slides.add();s.background.fill=C.white;tx(s,"BOTTOM LINE",48,44,230,30,19,true,C.blue);tx(s,"Advance TFT — then prove it",48,142,1040,110,66,true);tx(s,"Leading candidate",48,312,360,50,31,true,C.purple);tx(s,"Lowest RMSE and the only model with positive out-of-sample R².",48,373,520,74,24);tx(s,"Before production",660,312,360,50,31,true);tx(s,"Rolling origins · 30/90-day horizons · per-site forecasts · calibrated intervals · naive baselines",660,373,520,112,24);box(s,48,548,1144,8,C.blue,C.blue);tx(s,"Use TFT for the next experiment, not yet as the final answer.",48,584,1144,52,29,true);notes(s,"Treat TFT as the leading candidate, not a finished production model. Validate it across seeds and rolling origins, shorten the horizon, forecast each site separately, recalibrate intervals, and keep naive baselines visible.",[nb])}

await fs.mkdir(OUT,{recursive:true});for(const [i,s] of p.slides.items.entries()){const stem=`slide-${String(i+1).padStart(2,"0")}`;await wb(path.join(OUT,stem+".png"),await p.export({slide:s,format:"png",scale:1}));await fs.writeFile(path.join(OUT,stem+".layout.json"),await(await s.export({format:"layout"})).text())}await wb(path.join(OUT,"montage.webp"),await p.export({format:"webp",montage:true,scale:1}));const q=await p.inspect({kind:"slide,textbox,shape,image,chart,notes",maxChars:12000});await fs.writeFile(path.join(OUT,"inspect.ndjson"),q.ndjson);const f=await PresentationFile.exportPptx(p);await f.save(path.join(ROOT,"data_analysis_days_model_comparison.pptx"));console.log("done");
